### ISSUE TITLE
Direct messages to bot responds to slackbot channel

### ISSUE THREAD

**Issue by Sjeanpierre** [inkel/hubot-slack-attachment#2]
Hey Leandro, I really appreciate you writing this package.

When I send a direct message to my bot I expect it to respond in the same channel similar to how it behaves when using the send function. Is this an incorrect assumption?

**Comment by inkel** [comment]
> Hey Leandro, I really appreciate you writing this package.

Thank you!!! :heart_eyes_cat: 

> When I send a direct message to my bot I expect it to respond in the same channel similar to how it behaves when using the send function. Is this an incorrect assumption?

I'm not 100% of understanding what you're saying. You mean you `/dm yourbot something` and it's sending the response in a different channel?

Thank you for your time using this package and sending feedback!

**Comment by Sjeanpierre** [comment]
So I select my bot in my direct message area and send him a message that he would understand and respond to
![slack](https://cloud.githubusercontent.com/assets/673382/5858688/15fb4dd2-a223-11e4-8526-2ebddd8b3c81.jpg)

My only issue is that instead of responding in the same DM room
![slack](https://cloud.githubusercontent.com/assets/673382/5858733/6a131008-a223-11e4-974f-33c918ecfa02.jpg)
He responds in the slackbot room
![slack_and_postman](https://cloud.githubusercontent.com/assets/673382/5858808/087e63aa-a224-11e4-832e-9b02697762e0.jpg)

**Comment by inkel** [comment]
Ah, yes, that's what I thought. I think this is a limitation on Slack's part, but I've to confirm it. When they rolled out the newest version of [`hubot-slack`](https://github.com/slackhq) they [left out attachments](https://github.com/slackhq/hubot-slack/issues/108), and the only solution I've found was using the [Incoming Webhooks](https://api.slack.com/incoming-webhooks) API, and in that case it is not a your bot the one sending the message, but `slackbot`, thus the reason why it doesn't appear in your bot's DM channel.

Please take this with a grain of salt, I might be wrong with my findings. I need to investigate the latest changes to `hubot-slack` and see if I can find a way to implement sending this payload through their API.

**Comment by Sjeanpierre** [comment]
Ok, I appreciate you getting back to me about this. I kind of suspected that this was the case, but I was just making sure.

**Comment by inkel** [comment]
Hi @Sjeanpierre, the [`hubot-slack`](https://github.com/slackhq/hubot-slack) adapter is on the verge of [reimplementing `slack.attachment`](https://github.com/slackhq/hubot-slack/pull/148), so perhaps this will work as expected in the future. I'll post an update once that pull request is merged or not.

**Comment by Sjeanpierre** [comment]
Thanks for keeping me updated @inkel

**Comment by iwege** [comment]
Hi @inkel , the hubot-slack adapter have [reimplemented the slack.attachment event ](https://github.com/slackhq/hubot-slack/commit/471e71dea0acdf000f1fb0dfa621156d61148e8e)handle. I think maybe the hubot-jenkins-slack need to recommend to use the official adapter.

**Comment by MeLight** [comment]
Did you guys solve this problem? Does your bot sends the message in DM, or still as the slackbot?

**Comment by Sjeanpierre** [comment]
Yeah this issue was resolved with the commit above your comment.
